### ISSUE TITLE
Can't open some gifs

### ISSUE THREAD

**Issue by s4chin** [kaitai-io/kaitai_struct_formats#21]
There are some gifs that cannot be opened by the parser obtained from `gif.ksy`, these can be opened in the browser, on desktop and also by Pillow. The below gif is one example taken from the Pillow repository.
![iss634](https://cloud.githubusercontent.com/assets/5997735/22695242/2357a3b4-ed70-11e6-868a-2308ebbaa74f.gif)

I'm using python 3.5 and the error is -
```py
>>> a = Gif.from_file('iss634.gif')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/s4chin/.virtualenvs/kaitai/lib/python3.5/site-packages/kaitaistruct.py", line 28, in from_file
    return cls(KaitaiStream(f))
  File "/home/s4chin/img/gif.py", line 35, in __init__
    self.blocks.append(self._root.Block(self._io, self, self._root))
  File "/home/s4chin/img/gif.py", line 146, in __init__
    self.block_type = self._root.BlockType(self._io.read_u1())
  File "/usr/lib/python3.5/enum.py", line 241, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.5/enum.py", line 476, in __new__
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 166 is not a valid BlockType
```

**Comment by GreyCat** [comment]
That was because local color table weren't implemented. Fixed in https://github.com/kaitai-io/kaitai_struct_formats/commit/562154250bea0081fed4e232751b934bc270a0c7 — your files seems to be parsed properly now. There are 86 blocks detected now:

* 1 netscape animation block
* 42 * 2 blocks (per 42 animation frames) = graphic control block + local image descriptor
* 1 end of file block

**Comment by s4chin** [comment]
That was fast! Thanks!
