### ISSUE TITLE
gif declaration incorrect (yaml parsing error)

### ISSUE THREAD

**Issue by tpetry** [kaitai-io/kaitai_struct_formats#274]
The `Try It` functionality has problems parsing the gif declaration, maybe the declaration format is outdated?

``io.kaitai.struct.format.YAMLParseException: /seq/2/doc-ref: unknown key found, expected: consume, contents, doc, eos-error, id, if, include, parent, process, repeat, size, size-eos, terminator, type``

Additionally (maybe related?) the block diagram at the website is missing the image for the gif format:
http://formats.kaitai.io/gif/index.html

**Comment by generalmimon** [comment]
@tpetry Good catch! There actually was an error in the KSY spec (fixed in https://github.com/kaitai-io/kaitai_struct_formats/commit/19cc797f9b624a059da8502bf1456347d4960992), that's why the Graphviz block diagram was missing in the formats gallery.

It doesn't work in REPL tool (the `Try it` page), because the REPL is outdated, please use the Web IDE on https://ide.kaitai.io/devel/ instead. Read https://github.com/kaitai-io/kaitai_struct/issues/146#issuecomment-586013026 for more info.
